version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: julix
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - './data:/data/db'
    ports:
      - '27017:27017'
  node:
    build:
      context: ..
      dockerfile: ./docker/node.dockerfile
    volumes:
      - '../:/app'
  nginx:
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    volumes:
      - '../assets/images:/images'
      - '../../client/build:/usr/share/nginx/html/'
    ports:
      - 8080:80
